### PR TITLE
fix http protocol to https in template url's

### PR DESCRIPTION
**Pull request by ajnyga**
See rkhalikov's post here: http://forum.pkp.sfu.ca/t/ojs-share-this-social-media/679/14?u=ajnyga

### CODE REVIEW

**Comment by asmecher** [comment]
I think it would be better to make these links protocol-relative, so the browser would fetch them using the same protocol (`http` or `https`) that's being used to fetch the rest of the site, no?

**Comment by ajnyga** [comment]
true, wait

**Comment by ajnyga** [comment]
there, bumped into this btw. https://jeremywagner.me/blog/stop-using-the-protocol-relative-url

Also: https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by asmecher** [comment]
Interesting -- thanks, @ajnyga. Frankly we have a lot of work to do before we have to worry about the level of finesse in consideration per that post -- most of our users are still using `http` on shared hosting. But it's worth keeping ahead of things, and evidently I have some reading to do. Meanwhile, I'll merge this as is -- we already use protocol-relative links in cases like this (IIRC we even recently fixed this exact case on the OJS 2.x codebase).

**Comment by ajnyga** [comment]
Definitely, I just had to check that I write to protocol relative url's the right way and that was the top google hit :)

**Pull request merged**
